name: PharmaciesDevelopment

on:
  push:
    branches:
      - dev


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout and copy code to workflow
        uses: actions/checkout@v2

      - name: Set up Java JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'adopt'

      - name: Install Spring backend
        run: |
          cd pharmacies
          mvn clean install -U
          mvn clean package
          mvn clean test jacoco:report

      - name: jaCoCo Reports
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: pharmacies/target/site/jacoco

  delivery:
    runs-on: ubuntu-latest
    needs: build

    env:
      PROJECT_ID: ${{ secrets.PROJECT_ID }}
      USER_VM: ${{ secrets.USER_VM }}  
      VM_NAME: ${{ secrets.VM_NAME }} 
      ZONE: ${{ secrets.ZONE }} 
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}

    steps:
      # Copy code to runner environment
      - name: Checkout and copy code to workflow
        uses: actions/checkout@v2

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Auth Dockerhub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Auth GCP
      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: 'Use gcloud CLI'
        run: 'gcloud info'

      # Configure image
      - name: Build and Push Docker Image
        env: 
          NAME: hospital_pharmacies_backend
        run: |
          docker build -f pharmacies/Dockerfile -t ${{ env.NAME }}:latest ./pharmacies
          docker tag ${{ env.NAME }}:latest ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.NAME }}:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.NAME }}:latest

      # DEPLOY  
      - name: 'Execute script on VM'
        run: |
          gcloud compute ssh ${{ env.USER_VM }}@${{ env.VM_NAME }} --zone=${{ env.ZONE }} --command="cd project/pharmacies && bash deploy.sh"
